<a href="https://colab.research.google.com/github/LatiefDataVisionary/healthcare-test-results-prediction/blob/main/Untitled42.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
# The error indicates that the file_path was empty. We need to provide a valid file path within the dataset.
# A common file extension for this type of dataset is .csv.
file_path = "healthcare_dataset.csv" # Replace with the actual filename if different

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "prasad22/healthcare-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipython-input-3584434938.py:12: DeprecationWarning: load_dataset is deprecated and will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:             Name  Age  Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30    Male         B-            Cancer        2024-01-31
1   LesLie TErRy   62    Male         A+           Obesity        2019-08-20
2    DaNnY sMitH   76  Female         A-           Obesity        2022-09-22
3   andrEw waTtS   28  Female         O+          Diabetes        2020-11-18
4  adrIENNE bEll   43  Female        AB+            Cancer        2022-09-19

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross
1   Samantha Davies                     Kim Inc           Medicare
2  Tiffany Mitchell                    Cook PLC              Aetna
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare
4    Kathleen Hanna                 White-White              Aetna

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0    18856.281306          328         Urgent     2024-02-02  Paracetamol
1    33643.327287          265      Emergency     2019-08-26    Ibuprofen
2    27955.096079          205      Emergency     2022-10-07      Aspirin
3    37909.782410          450       Elective     2020-12-18    Ibuprofen
4    14238.317814          458         Urgent     2022-10-09   Penicillin

   Test Results
0        Normal
1  Inconclusive
2        Normal
3      Abnormal
4      Abnormal

In [3]:
df.head(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive
8,JASmINe aGuIlaR,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.222792,316,Elective,2020-07-14,Aspirin,Abnormal
9,ChRISTopher BerG,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.631062,249,Elective,2021-06-22,Paracetamol,Inconclusive

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [5]:
df.describe(include='all')

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
count,55500,55500.000000,55500,55500,55500,55500,55500,55500,55500,55500.000000,55500.000000,55500,55500,55500,55500
unique,49992,NaN,2,8,6,1827,40341,39876,5,NaN,NaN,3,1856,5,3
top,DAvId muNoZ,NaN,Male,A-,Arthritis,2024-03-16,Michael Smith,LLC Smith,Cigna,NaN,NaN,Elective,2020-03-15,Lipitor,Abnormal
freq,3,NaN,27774,6969,9308,50,27,44,11249,NaN,NaN,18655,53,11140,18627
mean,NaN,51.539459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25539.316097,301.134829,NaN,NaN,NaN,NaN
std,NaN,19.602454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14211.454431,115.243069,NaN,NaN,NaN,NaN
min,NaN,13.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2008.492140,101.000000,NaN,NaN,NaN,NaN
25%,NaN,35.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13241.224652,202.000000,NaN,NaN,NaN,NaN
50%,NaN,52.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25538.069376,302.000000,NaN,NaN,NaN,NaN
75%,NaN,68.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37820.508436,401.000000,NaN,NaN,NaN,NaN
max,NaN,89.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52764.276736,500.000000,NaN,NaN,NaN,NaN

In [7]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(534)

In [9]:
for col in df.columns:
    unique_values = df[col].unique()
    print(f"Unique values in column '{col}': \n\t{unique_values}\n")

Unique values in column 'Name':
	['Bobby JacksOn' 'LesLie TErRy' 'DaNnY sMitH' ... 'LiSa sIMPsoN'
 'RoGER farRELl' 'kaTheRIne WeBSTer']

Unique values in column 'Age':
	[30 62 76 28 43 36 21 20 82 58 72 38 75 68 44 46 63 34 67 48 59 73 51 23
 78 25 33 26 70 57 74 81 49 65 31 22 77 42 24 84 55 40 83 18 27 19 29 61
 80 60 35 79 53 69 47 85 52 37 50 32 54 45 66 39 56 64 71 41 88 17 87 86
 15 16 13 14 89]

Unique values in column 'Gender':
	['Male' 'Female']

Unique values in column 'Blood Type':
	['B-' 'A+' 'A-' 'O+' 'AB+' 'AB-' 'B+' 'O-']

Unique values in column 'Medical Condition':
	['Cancer' 'Obesity' 'Diabetes' 'Asthma' 'Hypertension' 'Arthritis']

Unique values in column 'Date of Admission':
	['2024-01-31' '2019-08-20' '2022-09-22' ... '2019-05-31' '2023-10-12'
 '2021-03-14']

Unique values in column 'Doctor':
	['Matthew Smith' 'Samantha Davies' 'Tiffany Mitchell' ... 'Deborah Sutton'
 'Mary Bartlett' 'Alec May']

Unique values in column 'Hospital':
	['Sons and Miller' 'Kim Inc' 'Cook PLC' ... 'Guzman Jones and Graves,'
 'and Williams, Brown Mckenzie' 'Moreno Murphy, Griffith and']

Unique values in column 'Insurance Provider':
	['Blue Cross' 'Medicare' 'Aetna' 'UnitedHealthcare' 'Cigna']

Unique values in column 'Billing Amount':
	[18856.28130598 33643.32728658 27955.09607884 ...  8441.14706442
 34934.2841126   8926.28593733]

Unique values in column 'Room Number':
	[328 265 205 450 458 389 277 316 249 394 288 134 309 182 465 114 449 260
 115 295 327 119 109 162 401 157 223 293 371 108 245 494 285 228 481 212
 113 272 478 196 418 410 300 211 413 138 456 234 492 180 250 296 330 405
 306 333 244 325 378 468 368 263 489 241 231 377 407 135 131 102 255 422
 320 273 395 152 321 428 482 268 120 318 144 226 459 208 227 402 442 425
 373 290 361 251 440 414 424 307 476 388 326 178 177 302 130 430 133 104
 408 376 331 275 480 233 384 380 310 406 213 427 500 451 485 267 154 466
 453 261 167 179 490 258 483 202 198 308 278 103 400 192 128 238 136 218
 348 486 147 126 314 271 341 498 168 189 438 286 266 392 156 315 322 184
 472 398 435 174 137 111 464 117 493 183 471 164 356 497 421 488 317 247
 158 242 151 221 359 370 141 343 319 121 166 397 186 299 101 142 181 282
 350 262 210 391 195 214 409 279 243 106 467 176 287 124 352 165 347 354
 225 357 140 404 426 236 194 188 415 185 358 390 112 283 439 123 469 230
 171 484 256 365 452 172 197 110 437 419 416 461 431 105 313 385 116 386
 175 270 338 360 252 215 434 374 217 366 118 387 237 355 364 169 301 463
 382 232 455 462 393 423 264 289 342 292 146 193 148 441 199 216 132 475
 436 403 433 206 207 375 159 304 349 396 445 276 298 129 209 420 324 443
 254 470 346 496 448 280 335 411 200 312 305 345 145 203 362 454 191 339
 477 219 412 379 340 170 190 363 491 487 334 125 332 224 204 323 248 297
 311 201 143 107 303 329 122 337 457 274 246 294 161 336 383 187 229 291
 155 173 353 281 446 399 479 429 150 253 149 369 220 127 153 474 372 381
 473 351 259 257 367 222 460 447 495 344 163 139 444 284 499 432 269 160
 240 239 417 235]

Unique values in column 'Admission Type':
	['Urgent' 'Emergency' 'Elective']

Unique values in column 'Discharge Date':
	['2024-02-02' '2019-08-26' '2022-10-07' ... '2019-05-09' '2024-05-31'
 '2024-06-06']

Unique values in column 'Medication':
	['Paracetamol' 'Ibuprofen' 'Aspirin' 'Penicillin' 'Lipitor']

Unique values in column 'Test Results':
	['Normal' 'Inconclusive' 'Abnormal']

In [10]:
# Ambil 10 baris acak dari DataFrame
display(df.sample(10))

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
4480,TIMOTHY BeLL,18,Male,O+,Hypertension,2021-02-27,Monique Hays,Ruiz-Wilson,Aetna,25822.469251,102,Emergency,2021-03-26,Penicillin,Abnormal
20985,calVIn BrOWN,41,Female,B+,Hypertension,2021-10-06,Alexandra Meyers,Lee-Meyer,Aetna,39194.543825,286,Elective,2021-10-19,Lipitor,Normal
20512,tamMy myErs pHd,23,Male,AB+,Cancer,2022-05-13,Mr. Melvin Guzman Jr.,Thomas-Lawson,Blue Cross,8029.469958,194,Elective,2022-06-04,Penicillin,Normal
22337,treVoR powELl,27,Male,B+,Hypertension,2020-08-01,Jessica Weiss,Winters-Carter,Blue Cross,1697.770661,443,Urgent,2020-08-29,Lipitor,Inconclusive
11860,eduARdo LUNA,51,Female,B+,Asthma,2022-08-31,Samuel Kerr,Smith-Powers,Medicare,36888.105415,280,Urgent,2022-09-20,Ibuprofen,Inconclusive
28589,TaYLoR RANdAll,52,Female,AB+,Asthma,2022-02-07,Brittany Miller,Long-Christensen,Medicare,21444.221490,362,Emergency,2022-02-09,Ibuprofen,Inconclusive
15019,jErry GUTIeRrez,33,Female,A-,Asthma,2023-10-20,Greg Sullivan,Ltd Cortez,Medicare,4302.414745,433,Emergency,2023-11-01,Aspirin,Normal
41898,marK GARCIA,47,Male,B-,Hypertension,2022-03-15,Julie Holmes,"Gallagher, Hughes and Palmer",Aetna,16378.603026,231,Urgent,2022-03-23,Lipitor,Inconclusive
52763,aArON MArTineZ,36,Male,O+,Cancer,2019-08-27,Carol Smith,Tran LLC,Medicare,23011.552669,126,Emergency,2019-09-15,Paracetamol,Inconclusive
40945,rIcHaRD perEz,70,Female,O+,Obesity,2022-04-12,Laura Burton,"Lindsey Berger, and Dunn",Aetna,43106.954306,216,Elective,2022-04-13,Aspirin,Inconclusive